export const GAMES = [
    { id: 'apple-tree', name: 'شجرة التفاح', desc: 'لعبة ممتعة لجمع وطرح الأرقام', color: 'bg-red-50 text-red-700' },
    { id: 'balance-scale', name: 'ميزان الأبطال', desc: 'لعبة لتفهم التوازن في المعادلات', color: 'bg-green-50 text-green-700' },
    { id: 'crocodile', name: 'التمساح الجائع', desc: 'مقارنة الأرقام باستخدام التمساح', color: 'bg-teal-50 text-teal-700' },
    { id: 'fraction-pizza', name: 'بيتزا الكسور', desc: 'لعبة لتفهم الكسور وتطبيقاتها', color: 'bg-yellow-50 text-yellow-700' },
    { id: 'jumping-frog', name: 'الضفدع القافز', desc: 'لعبة للقفز على خط الأعداد', color: 'bg-lime-50 text-lime-700' },
    { id: 'missing-train', name: 'قطار الأرقام', desc: 'اكتشف الأرقام الناقصة في القطار', color: 'bg-blue-50 text-blue-700' },
    { id: 'numbers-vault', name: 'خزنة الأرقام', desc: 'التعرف على الآحاد والعشرات', color: 'bg-gray-50 text-gray-700' },
    { id: 'place-value-castle', name: 'قلعة الآحاد والعشرات', desc: 'لعبة بناء القيم المكانية', color: 'bg-purple-50 text-purple-700' },
    { id: 'rounding-coaster', name: 'قطار التقريب', desc: 'تقريب الأرقام بطريقة سريعة', color: 'bg-orange-50 text-orange-700' },
    { id: 'shape-detective', name: 'المحقق الذكي', desc: 'تعرف على الأشكال الهندسية', color: 'bg-cyan-50 text-cyan-700' },
    { id: 'space-bubbles', name: 'فقاعات الفضاء', desc: 'العمليات الحسابية في الفضاء', color: 'bg-fuchsia-50 text-fuchsia-700' },
    { id: 'number-deconstructor', name: 'مفكك الأرقام', desc: 'التدريب على القيمة المنزلية للأرقام', color: 'bg-amber-50 text-amber-700' },
    { id: 'candy-factory', name: 'مصنع الحلوى', desc: 'تعلّم الضرب بترتيب الحلوى في صفوف وأعمدة', color: 'bg-pink-50 text-pink-700' },
    { id: 'heroes-market', name: 'سوق الأبطال', desc: 'كن أمهر بائع واحسب الباقي بدقة', color: 'bg-emerald-50 text-emerald-700' },
    { id: 'division-pirates', name: 'قراصنة القسمة', desc: 'وزع الكنز بالتساوي مع القبطان', color: 'bg-stone-50 text-stone-700' },
    { id: 'farm-fence', name: 'سياج المزرعة', desc: 'حساب محيط الحقل لبناء سياج حوله', color: 'bg-lime-50 text-lime-700' },
    { id: 'symmetry-butterfly', name: 'فراشة التماثل', desc: 'طابق النصف الآخر لتكتمل الفراشة', color: 'bg-fuchsia-100 text-fuchsia-900' },
    { id: 'space-defender', name: 'حارس الفضاء', desc: 'دمر النيازك بأسلحة الضرب قبل أن تضرب الكوكب', color: 'bg-cyan-50 text-cyan-700' },
    { id: 'clever-builder', name: 'البناء الماهر', desc: 'استخدم المسطرة لقياس القطع بدقة', color: 'bg-stone-50 text-stone-700' },
    { id: 'ice-cream-shop', name: 'متجر الآيس كريم', desc: 'اقرأ الأعمدة البيانية لنكهات الآيس كريم', color: 'bg-pink-50 text-pink-700' },
    { id: 'robot-sorter', name: 'فرّاز الروبوتات', desc: 'افحص التروس ورتّب الأعداد الزوجية والفردية', color: 'bg-slate-800 text-cyan-400' },
    { id: 'castle-cannon', name: 'مدفع القلعة', desc: 'حدد نوع الزاوية لضبط المدفع وحماية القلعة', color: 'bg-stone-900 text-amber-500' },
    { id: 'tile-painter', name: 'رسّام البلاط', desc: 'احسب مساحة الجزء الملون بالوحدات المربعة', color: 'bg-teal-50 text-teal-700' },
    { id: 'fractions-lab', name: 'معمل الكسور', desc: 'ابحث عن الكسور المتكافئة لإكمال التجربة العلمية', color: 'bg-emerald-900 text-emerald-400' },
    { id: 'train-journey', name: 'رحلة القطار', desc: 'اقرأ تذكرة السفر واحسب وقت الوصول بدقة', color: 'bg-amber-100 text-amber-900' },
    { id: 'treasure-map', name: 'خريطة الكنز', desc: 'حدد إحداثيات موقع الكنز على الشبكة', color: 'bg-orange-950 text-amber-500' },
    { id: 'probability-spinner', name: 'عجلة الاحتمالات', desc: 'توقع احتمالية وقوف المؤشر على الألوان', color: 'bg-purple-900 text-pink-300' },
    { id: 'gold-merchant', name: 'تاجر الذهب', desc: 'اختر وحدة الكتلة المناسبة للأشياء', color: 'bg-[#4a2e1b] text-amber-500' },
    { id: 'deep-sea-submarine', name: 'غواصة الأعماق', desc: 'اقرأ إحداثيات الأعماق العشرية لتصل للكنز', color: 'bg-cyan-950 text-cyan-300' },
    { id: 'mountain-climber', name: 'متسلق الجبال', desc: 'رتب الأعداد تصاعدياً للوصول للقمة', color: 'bg-sky-900 text-white' },
    { id: 'wizard-of-zeros', name: 'ساحر الأصفار', desc: 'استخدم الحساب الذهني للضرب في 10 و 100 و 1000', color: 'bg-[#1e1b4b] text-fuchsia-300' },
    { id: 'juice-maker', name: 'صانع العصائر', desc: 'اختر الوحدة المناسبة لقياس السعة', color: 'bg-orange-100 text-orange-600' },
];
