'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { getDifficultyMax, Difficulty } from '@/lib/difficulty';
import confetti from 'canvas-confetti';
import { motion, AnimatePresence } from 'framer-motion';

export default function JumpingFrogGamePage() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const studentId = searchParams.get('studentId');
  const isTeacher = searchParams.get('teacher') === 'true';
    const difficulty = (searchParams.get('difficulty') || 'medium') as Difficulty;
    const [gameStarted, setGameStarted] = useState(false);
    const [studentName, setStudentName] = useState('');

    type QuestionData = {
        start: number;
        jumps: number;
        step: number;
        correctAnswer: number;
        options: number[];
        isSubtraction: boolean;
    };

    const [questionData, setQuestionData] = useState<QuestionData | null>(null);
    const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);

    const [score, setScore] = useState(0);
    const [questionNumber, setQuestionNumber] = useState(0);
    const [feedback, setFeedback] = useState<'correct' | 'wrong' | null>(null);
    const [isAnimating, setIsAnimating] = useState(false);

    // Controls frog position internally during animation
    const [frogState, setFrogState] = useState<'idle' | 'jumping' | 'falling'>('idle');

    const [startTime, setStartTime] = useState<number>(0);

    const [settings, setSettings] = useState({
        successSoundUrl: '',
        errorSoundUrl: '',
        backgroundMusicUrl: '',
    });

    const totalQuestions = 10;

    useEffect(() => {
        fetch('/api/settings')
            .then((res) => res.json())
            .then((data) => setSettings(data))
            .catch((err) => console.error('Error loading settings:', err));
    }, []);

    const playSound = (url: string) => {
        if (url) {
            const audio = new Audio(url);
            audio.play().catch((err) => console.error('Error playing sound:', err));
        }
    };

    const generateQuestion = () => {
        setFeedback(null);
        setSelectedAnswer(null);
        setFrogState('idle');
        setIsAnimating(false);

        // Steps can be: 2, 3, 4, 5, 10
        const possibleSteps = [2, 3, 4, 5, 10];
        const step = possibleSteps[Math.floor(Math.random() * possibleSteps.length)];

        // Jumps 2 to 6
        const jumps = Math.floor(Math.random() * 5) + 2;

        // Start number scales with difficulty
        const start = Math.floor(Math.random() * getDifficultyMax(difficulty)) + 1;

        // Sometimes backward jumps (subtraction)
        const isSubtraction = Math.random() > 0.7 && start > (jumps * step);

        const correctAnswer = isSubtraction ? start - (jumps * step) : start + (jumps * step);

        const opts = new Set<number>();
        opts.add(correctAnswer);

        while (opts.size < 3) {
            // wrong options generated by changing jumping logic or off-by-one errors
            const wrongJump = jumps + (Math.random() > 0.5 ? 1 : -1);
            let wrongOpt1 = isSubtraction ? start - (wrongJump * step) : start + (wrongJump * step);

            const wrongOpt2 = correctAnswer + (Math.random() > 0.5 ? 1 : -1) * (step > 2 ? 1 : 2);

            const randWrong = Math.random() > 0.5 ? wrongOpt1 : wrongOpt2;

            if (randWrong > 0 && randWrong !== correctAnswer) {
                opts.add(randWrong);
            }
        }

        setQuestionData({
            start,
            jumps,
            step,
            correctAnswer,
            options: Array.from(opts).sort(() => Math.random() - 0.5),
            isSubtraction
        });
    };

    const startGame = () => {
        if (!studentName.trim() && !studentId && !isTeacher) {
            alert('يرجى إدخال اسمك أولاً');
            return;
        }
        setGameStarted(true);
        setScore(0);
        setQuestionNumber(1);
        setStartTime(Date.now());
        generateQuestion();
    };

    useEffect(() => {
        if ((studentId || isTeacher) && !gameStarted) {
            setGameStarted(true);
            setScore(0);
            setQuestionNumber(1);
            setStartTime(Date.now());
            generateQuestion();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [studentId, isTeacher, gameStarted]);


    const checkAnswer = (selectedOpt: number) => {
        if (feedback !== null || !questionData || isAnimating) return;

        setSelectedAnswer(selectedOpt);
        setIsAnimating(true);

        if (selectedOpt === questionData.correctAnswer) {
            setFeedback('correct');
            setScore(prev => prev + 1);
            playSound(settings.successSoundUrl);
            setFrogState('jumping');

            confetti({
                particleCount: 100,
                spread: 70,
                origin: { y: 0.6 },
                colors: ['#4ade80', '#22c55e', '#16a34a'],
            });

            setTimeout(() => {
                nextQuestion(true);
            }, 3000);
        } else {
            setFeedback('wrong');
            setFrogState('falling');
            playSound(settings.errorSoundUrl);

            setTimeout(() => {
                setFeedback(null);
                setSelectedAnswer(null);
                setFrogState('idle');
                setIsAnimating(false);
            }, 2500); // give time for falling animation
        }
    };

    const nextQuestion = (wasCorrect: boolean) => {
        if (questionNumber >= totalQuestions) {
            finishGame(wasCorrect);
        } else {
            setQuestionNumber(prev => prev + 1);
            generateQuestion();
        }
    };

    const finishGame = async (wasCorrect: boolean) => {
        const timeSpent = Math.floor((Date.now() - startTime) / 1000);
        const finalScore = wasCorrect ? score + 1 : score;

        try {
            if (!isTeacher) { await fetch('/api/scores', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    studentName: studentName || 'Student',
                    studentId: studentId || undefined,
                    score: finalScore,
                    totalQuestions,
                    timeSpent,
                    gameType: 'jumping-frog',
                }),
            }); }

            router.push(`/results?score=${finalScore}&total=${totalQuestions}&time=${timeSpent}&gameId=jumping-frog${studentId ? `&studentId=${studentId}` : ''}`);
        } catch (error) {
            console.error('Error saving score:', error);
            alert('حدث خطأ في حفظ النتيجة');
        }
    };

    if (!gameStarted) {
        return (
            <div className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-b from-cyan-400 to-blue-600 relative overflow-hidden" dir="rtl">
                {/* Pond Background */}
                <div className="absolute inset-0 opacity-40 bg-[url('https://www.transparenttextures.com/patterns/water.png')] mix-blend-overlay"></div>

                {/* Decorative Lilies */}
                <div className="absolute top-20 right-10 text-6xl opacity-60">🌸</div>
                <div className="absolute bottom-10 left-20 text-7xl opacity-80">🌿</div>
                <div className="absolute top-40 left-10 text-5xl opacity-40">💧</div>

                <div className="max-w-lg w-full relative z-10">
                    <div className="bg-white/95 backdrop-blur-md rounded-3xl shadow-[0_20px_60px_rgba(0,0,0,0.5)] p-8 text-center flex flex-col items-center border-[5px] border-emerald-500">
                        <div className="mb-4 text-8xl drop-shadow-[0_10px_10px_rgba(22,163,74,0.5)]">
                            🐸
                        </div>
                        <h1 className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-green-800 mb-4 drop-shadow-sm">
                            الضفدع القافز
                        </h1>
                        <p className="text-xl text-emerald-900 mb-8 font-bold">
                            ساعد الضفدع في القفز عبر الأرقام للوصول للضفة الأخرى! 🌊
                        </p>

                        <div className="mb-6 w-full">
                            <label htmlFor="name" className="block text-emerald-800 font-bold mb-2 text-right text-lg">
                                ما اسمك أيها اللاعب الماهر؟
                            </label>
                            <input
                                type="text"
                                id="name"
                                value={studentName}
                                onChange={(e) => setStudentName(e.target.value)}
                                className="w-full px-4 py-4 bg-emerald-50 border-2 border-emerald-300 rounded-xl focus:border-emerald-500 focus:outline-none transition-all text-emerald-900 placeholder-emerald-400/80 text-center text-xl font-black shadow-inner"
                                placeholder="اكتب اسمك هنا"
                                required
                            />
                        </div>

                        <button
                            onClick={startGame}
                            className="w-full bg-gradient-to-r from-emerald-500 to-green-600 hover:from-emerald-400 hover:to-green-500 text-white font-black text-2xl py-5 rounded-xl shadow-[0_6px_0_#14532d] active:shadow-[0_0px_0_#14532d] active:translate-y-2 transform transition-all border border-emerald-300/50"
                        >
                            ابدأ القفز 🐸
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen flex flex-col items-center justify-start pt-24 sm:pt-28 pb-8 px-4 sm:px-8 bg-gradient-to-b from-cyan-300 via-blue-400 to-indigo-600 relative overflow-hidden" dir="rtl">

            {/* Water Texture */}
            <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/black-linen.png')] mix-blend-overlay pointer-events-none"></div>

            {/* Floating Water Ripples (CSS Only) */}
            <div className="absolute top-1/3 left-1/4 w-32 h-16 border-2 border-white/20 rounded-[100%] absolute animate-ping opacity-20 pointer-events-none"></div>
            <div className="absolute bottom-1/4 right-1/4 w-48 h-24 border-2 border-white/20 rounded-[100%] absolute animate-ping opacity-20 pointer-events-none" style={{ animationDelay: '1s' }}></div>

            {/* HUD */}
            <div className="fixed top-6 left-0 w-full px-6 flex justify-between items-start z-30 pointer-events-none">
                <div className="bg-white/90 backdrop-blur-sm rounded-2xl p-4 border-4 border-emerald-300 shadow-xl flex flex-col pointer-events-auto">
                    <span className="text-2xl font-black text-emerald-800">الضفدع {questionNumber}/{totalQuestions}</span>
                    <span className="text-xl font-bold text-emerald-600">النقاط: {score} 🏆</span>
                </div>
            </div>

            {questionData && (
                <>
                    {/* Question Title Header */}
                    <motion.div
                        initial={{ y: -50, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        className="mb-8 z-20 w-full max-w-4xl pt-4"
                    >
                        <div className="bg-emerald-900/80 backdrop-blur-md rounded-3xl p-6 sm:px-12 shadow-[0_10px_30px_rgba(0,0,0,0.4)] border-4 border-emerald-400/50 text-center relative overflow-hidden">
                            <h2 className="text-2xl sm:text-4xl font-black text-white drop-shadow-lg leading-relaxed relative z-10">
                                الضفدع يقف عند العدد <span className="text-amber-300 text-5xl inline-block mx-2">{questionData.start}</span>.
                                <br />
                                سيقفز <span className="text-emerald-300 text-4xl">{questionData.jumps} قفزات</span>، كل قفزة بـ <span className="text-orange-300 text-4xl">{questionData.isSubtraction ? '-' : '+'}{questionData.step}</span>.
                                <br />
                                <span className="text-cyan-200 mt-2 block">أين سيصل؟</span>
                            </h2>
                            {/* Decoration inside header */}
                            <div className="absolute top-2 left-4 text-5xl opacity-20 transform -rotate-12">🌿</div>
                            <div className="absolute bottom-2 right-4 text-5xl opacity-20 transform rotate-12">🌊</div>
                        </div>
                    </motion.div>

                    {/* Pond Area - Number Line */}
                    <div className="w-full max-w-5xl flex flex-col items-center justify-center relative mt-8 sm:mt-16 z-10 h-64 sm:h-80">
                        {/* The River/Number Line Visualization */}

                        <div className="relative w-full h-full flex items-center justify-center">

                            {/* Lily Pad Start (Right Side - RTL) */}
                            <div className="absolute right-[5%] sm:right-[15%] bottom-[20%] z-10">
                                <motion.div
                                    className="w-32 h-16 sm:w-40 sm:h-20 bg-green-500 rounded-[100%] border-b-8 border-green-700 shadow-xl relative flex items-center justify-center transform -rotate-3"
                                    animate={frogState === 'idle' ? { y: [0, -5, 0] } : {}}
                                    transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                                >
                                    {/* Lily Pad Cutout */}
                                    <div className="absolute top-0 right-4 w-0 h-0 border-l-[15px] border-l-transparent border-t-[20px] border-t-cyan-400 border-r-[15px] border-r-transparent"></div>
                                    <span className="text-white font-black text-3xl sm:text-4xl drop-shadow-md z-20">
                                        {questionData.start}
                                    </span>
                                </motion.div>
                            </div>

                            {/* The Frog */}
                            <motion.div
                                className="absolute right-[5%] sm:right-[15%] bottom-[20%] w-32 sm:w-40 h-16 sm:h-20 flex items-end justify-center z-30 pointer-events-none"
                                animate={
                                    frogState === 'jumping'
                                        ? {
                                            // Jump across the screen to the left using bezier curve approximation
                                            x: [-0, -200, -400, -600],
                                            y: [-20, -150, -100, -20],
                                            scale: [1, 1.2, 1.1, 1],
                                            rotate: [-10, -20, -10, 0]
                                        }
                                        : frogState === 'falling'
                                            ? {
                                                // Jump up and splash down
                                                y: [-20, -150, 50, 100],
                                                scale: [1, 1.1, 0.8, 0],
                                                rotate: [0, 45, 180, 360],
                                                opacity: [1, 1, 0.5, 0]
                                            }
                                            : { y: [-20, -25, -20] } // idle breathing
                                }
                                transition={
                                    frogState === 'jumping'
                                        ? { duration: 1.5, ease: "easeInOut", times: [0, 0.4, 0.7, 1] }
                                        : frogState === 'falling'
                                            ? { duration: 1.5, ease: "easeInOut" }
                                            : { duration: 2, repeat: Infinity, ease: "easeInOut" }
                                }
                                onAnimationComplete={() => {
                                    if (frogState === 'falling') {
                                        // add splash particle if needed, currently just hiding frog
                                    }
                                }}
                            >
                                <span className={`text-7xl sm:text-8xl drop-shadow-[0_10px_10px_rgba(0,0,0,0.5)] transform ${frogState === 'jumping' ? '' : ''}`}>
                                    🐸
                                </span>
                            </motion.div>

                            {/* Target Area (Left Side - RTL) - Only show clearly if answering */}
                            <AnimatePresence>
                                {(frogState === 'jumping' || feedback === 'correct') && (
                                    <motion.div
                                        initial={{ opacity: 0, scale: 0 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        className="absolute left-[5%] sm:left-[15%] bottom-[20%] z-10"
                                    >
                                        <div className="w-32 h-16 sm:w-40 sm:h-20 bg-emerald-400 rounded-[100%] border-b-8 border-emerald-600 shadow-xl relative flex items-center justify-center transform rotate-3">
                                            <div className="absolute top-0 left-4 w-0 h-0 border-l-[15px] border-l-transparent border-t-[20px] border-t-cyan-400 border-r-[15px] border-r-transparent"></div>
                                            <span className="text-white font-black text-3xl sm:text-4xl drop-shadow-md z-20">
                                                {questionData.correctAnswer}
                                            </span>
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {/* Water splash for falling */}
                            <AnimatePresence>
                                {frogState === 'falling' && (
                                    <motion.div
                                        initial={{ opacity: 0, scale: 0, y: 50 }}
                                        animate={{ opacity: [0, 1, 0], scale: [0, 2, 3], y: [50, 30, 0] }}
                                        exit={{ opacity: 0 }}
                                        transition={{ duration: 1, delay: 0.8 }} // delays to match frog entering water
                                        className="absolute right-[5%] sm:right-[15%] bottom-[20%] text-6xl pointer-events-none z-40"
                                    >
                                        💦
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {/* Jump Indicators (Arcs) - visual decoration */}
                            <svg className="absolute w-full h-[200px] top-0 pointer-events-none" preserveAspectRatio="none">
                                {/* Only show roughly if we want to hint the jumps. We skip complex dynamic SVG paths for simplicity and keep the focus on mental math, but we can draw a generic dashed line. */}
                                <path d="M 80% 80% Q 50% -20% 20% 80%" fill="none" stroke="rgba(255,255,255,0.3)" strokeWidth="6" strokeDasharray="10, 15" strokeLinecap="round" />
                            </svg>
                        </div>
                    </div>

                    {/* Answer Options Controls */}
                    <div className="mt-6 sm:mt-10 flex gap-4 sm:gap-8 justify-center w-full z-20 px-4 mb-20 flex-wrap">
                        {questionData.options.map((opt, i) => (
                            <motion.button
                                key={`opt-${i}`}
                                whileHover={{ scale: 1.05, y: -5 }}
                                whileTap={{ scale: 0.95 }}
                                onClick={() => checkAnswer(opt)}
                                disabled={isAnimating || feedback !== null}
                                className={`
                                    w-32 h-20 sm:w-48 sm:h-24 
                                    ${(selectedAnswer === opt && feedback === 'correct') ? 'bg-emerald-500 border-emerald-700 text-white' :
                                        (selectedAnswer === opt && feedback === 'wrong') ? 'bg-red-500 border-red-700 text-white' :
                                            'bg-green-400 hover:bg-green-300 border-green-600 text-green-900'} 
                                    border-b-[8px] text-4xl sm:text-5xl font-black 
                                    rounded-[100%] shadow-[0_15px_30px_rgba(0,0,0,0.3)] 
                                    disabled:opacity-50 disabled:cursor-not-allowed transition-colors
                                    flex items-center justify-center relative
                                `}
                            >
                                {/* Lily pad cutout styling on buttons too! */}
                                <div className={`absolute top-0 right-4 w-0 h-0 border-l-[10px] border-l-transparent border-t-[15px] ${(selectedAnswer === opt && feedback === 'wrong') ? 'border-t-indigo-600' : 'border-t-indigo-600'} border-r-[10px] border-r-transparent mix-blend-overlay opacity-30`}></div>

                                <span className="drop-shadow-sm z-10">{opt}</span>
                            </motion.button>
                        ))}
                    </div>

                    {/* Feedback Pop-up Overlay */}
                    <AnimatePresence>
                        {feedback && (
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm pointer-events-none"
                            >
                                <motion.div
                                    initial={{ scale: 0.5, y: 50 }}
                                    animate={{ scale: 1, y: 0 }}
                                    exit={{ scale: 0.5, opacity: 0 }}
                                    className={`max-w-lg w-full rounded-3xl p-8 text-center shadow-[0_20px_50px_rgba(0,0,0,0.5)] border-[6px] pointer-events-auto mt-40 ${feedback === 'correct' ? 'bg-gradient-to-br from-emerald-100 to-green-50 border-emerald-500 text-emerald-800' : 'bg-gradient-to-br from-cyan-100 to-blue-50 border-blue-500 text-blue-800'}`}
                                >
                                    <div className="text-8xl mb-4 drop-shadow-md">
                                        {feedback === 'correct' ? '🐸✨' : '💦🏊‍♂️'}
                                    </div>
                                    <h2 className="text-3xl sm:text-5xl font-black mb-4 leading-tight">
                                        {feedback === 'correct' ? 'قفزة مثالية! 🐸' : 'سباحة ممتعة! لكن حاول القفز بدقة!'}
                                    </h2>
                                    {feedback === 'wrong' && (
                                        <p className="text-xl font-bold mt-2 text-blue-600">
                                            تذكر: {questionData.start} {questionData.isSubtraction ? '-' : '+'} ({questionData.jumps} × {questionData.step}) = <span className="text-emerald-600 bg-emerald-100 px-2 rounded">{questionData.correctAnswer}</span>
                                        </p>
                                    )}
                                </motion.div>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </>
            )}

        </div>
    );
}
